USE [master]
GO

/****** Object:  Database [Pizza]    Script Date: 19/04/2021 17:51:00 ******/
CREATE DATABASE [Pizza]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Pizza', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Pizza.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Pizza_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Pizza_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Pizza].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Pizza] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Pizza] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Pizza] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Pizza] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Pizza] SET ARITHABORT OFF 
GO

ALTER DATABASE [Pizza] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Pizza] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Pizza] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Pizza] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Pizza] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Pizza] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Pizza] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Pizza] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Pizza] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Pizza] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Pizza] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Pizza] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Pizza] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Pizza] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Pizza] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Pizza] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Pizza] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Pizza] SET RECOVERY FULL 
GO

ALTER DATABASE [Pizza] SET  MULTI_USER 
GO

ALTER DATABASE [Pizza] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Pizza] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Pizza] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Pizza] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Pizza] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Pizza] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Pizza] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Pizza] SET  READ_WRITE 
GO

