CREATE TABLE CIDADE (
	IDCIDADE INT NOT NULL PRIMARY KEY
	, ESTADO VARCHAR(120)
	, UF VARCHAR(2)
	, NOME VARCHAR(120)
	);

INSERT INTO CIDADE (IDCIDADE, ESTADO, UF, NOME) VALUES (4500, 'SANTA CATARINA', 'SC', 'FLORIANÓPOLIS'); 